version: '3'
services:
    api:
        build:
            dockerfile: Dockerfile.dev
            context: .
        volumes:
            - ./:/go/src
        ports:
            - "9999:9999"
            - "2345:2345"
        tty: true
        security_opt:
            - apparmor:unconfined
        cap_add:
            - SYS_PTRACE
    db:
      image: postgres:${POSTGRES_VERSION}
      container_name: postgresql_host
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
        PGDATA: /var/lib/postgresql/data/pgdata
        TZ: 'Asia/Tokyo'
      volumes:
          - ./infra/dbhandle/data:/var/lib/postgresql/data
          - ./infra/dbhandle/sql:/docker-entrypoint-initdb.d
          - ./infra/dbhandle/logs:/var/log
      ports:
        - ${DB_PORT}:${DB_PORT}
