version: '3'
services:
    api:
        build:
            dockerfile: Dockerfile.dev
            context: .
        volumes:
            - ./:/go/src
        ports:
            - "9999:9999"
            - "2345:2345"
        tty: true
        security_opt:
            - apparmor:unconfined
        cap_add:
            - SYS_PTRACE
    db:
        image: mysql:5.7.31
        container_name: mysql_host
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: golang_mysql_dev
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./db/sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
