version: '3'
services:
    api:
        build:
            dockerfile: Dockerfile.dev
            context: .
        volumes:
            - ./:/go/src
        ports:
            - "9999:9999"
            - "2345:2345"
        tty: true
        security_opt:
            - apparmor:unconfined
        cap_add:
            - SYS_PTRACE
    db:
      image: postgres:12
      container_name: postgresql_host
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: golang_psql_dev
        PGDATA: /var/lib/postgresql/data/pgdata
        TZ: 'Asia/Tokyo'
      volumes:
          - ./db/data:/var/lib/postgresql/data
          - ./db/sql:/docker-entrypoint-initdb.d
          - ./db/logs:/var/log
      ports:
        - 5432:5432
