FROM golang:1.16.2-alpine3.13 as builder


WORKDIR /go/src

COPY go.mod go.sum ./
RUN go mod download
RUN go get -u github.com/cosmtrek/air

COPY . ./

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
RUN apk add --no-cache \
        alpine-sdk \
        git

EXPOSE 9999

